services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      PMA_USER: exampleuser
      PMA_PASSWORD: examplepass
    ports:
      - "8080:80"
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
  phpmyadmin: